[features]
seeds = false
skip-lint = false
[programs.localnet]
multi_sig_wallet = "yqiXBbHxd9bQJ6u2bqjLkLvGQG4H9Nmxwfcivv2BLg3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/qbeetsu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
