[features]
seeds = false
skip-lint = false
[programs.localnet]
multi_sig_wallet = "7LVNpeotp6jC3QNUG8XyMwWTMXJWqbU4o55Z3jEZexrk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/qbeetsu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
